<a href="https://colab.research.google.com/github/Mir-Safwan-Marzouq/Deep-Learning/blob/main/4_Loss%20or%20cost%20function/Loss_or_cost_function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.3,0.7,1,0,0.5])

In [ ]:
def mae(y_true,y_predicted):
  total_error = 0
  for yt, yp in zip(y_true, y_predicted):
    print(yt,yp)

In [ ]:
mae(y_true, y_predicted)

0.3 1
0.7 1
1.0 0
0.0 0
0.5 1


**Mean Absolute Error**

In [ ]:
def mae(y_true, y_predicted):
  total_error=0
  for yt, yp in zip(y_true, y_predicted):
    total_error +=  abs(yt-yp)
  print("Total Error= ",total_error)
  mae = total_error / len(y_true)
  print("MAE= ", mae)
  return mae

In [ ]:
mae(y_true, y_predicted)

Total Error=  2.5
MAE=  0.5


0.5

Define MAE function using numpy

In [ ]:
y_predicted - y_true   # gives real difference if you have numpy array

array([ 0.7,  0.3, -1. ,  0. ,  0.5])

In [ ]:
np.abs(y_predicted-y_true)

array([0.7, 0.3, 1. , 0. , 0.5])

In [ ]:
np.mean(np.abs(y_true-y_predicted)) # mean absolute error

0.5

In [ ]:
np.sum(np.abs(y_true-y_predicted)) # total error

2.5

**Log Loss or binary cross entropy**

In [ ]:
np.log([0])

<ipython-input-37-faee82fd9f21>:1: RuntimeWarning: divide by zero encountered in log
  np.log([0])


array([-inf])

In [ ]:
np.log([0.000000000000000000000001])

array([-55.26204223])

In [ ]:
epsilon = 1e-15

In [ ]:
y_predicted

array([1, 1, 0, 0, 1])

In [ ]:
y_predicted_new = [max(i,epsilon) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [ ]:
y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]  # because log of 0 is undefined
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [ ]:
y_predicted_new = np.array(y_predicted_new)
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [ ]:
np.log(y_predicted)

<ipython-input-46-d8d657355a01>:1: RuntimeWarning: divide by zero encountered in log
  np.log(y_predicted)


array([  0.,   0., -inf, -inf,   0.])

In [ ]:
-np.mean(y_true * np.log(y_predicted_new) + (1-y_true) * np.log(1-y_predicted_new))

17.2696280766844

In [ ]:
def log_loss(y_true, y_predicted):
  y_predicted_new = [max(i,epsilon) for i in y_predicted]
  y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
  y_predicted_new = np.array(y_predicted_new)
  return -np.mean(y_true * np.log(y_predicted_new) + (1-y_true) * np.log(1-y_predicted_new))

In [ ]:
log_loss(y_true, y_predicted)

17.2696280766844